DELETE FROM activos 
DELETE FROM activosasientocontable  
DELETE FROM activosdepreciacion  
DELETE FROM activosmov  
DELETE FROM aplicactacab  
DELETE FROM aplicactadet  
DELETE FROM aplicapagcab  
DELETE FROM aplicapagdet  
DELETE FROM cierresmes  
DELETE FROM costos_temp  
DELETE FROM cta_dcto 
DELETE FROM cta_mvto 
DELETE FROM doc_fac  
DELETE FROM docreferencia  
DELETE FROM docreferenciadet 
DELETE FROM docreferenciaempresas  
DELETE FROM docreferenciaempresasdet  
DELETE FROM docventas  
DELETE FROM docventasdet  
DELETE FROM letras  
DELETE FROM letrasxpagar 
DELETE FROM movbancoscab  
DELETE FROM movbancoscab_log  
DELETE FROM movbancosdet  
DELETE FROM movbancosdet_log  
DELETE FROM movbancosdet_sincab  
DELETE FROM movcajasdet  
DELETE FROM movpend  
DELETE FROM pag_dcto 
DELETE FROM pag_mvto 
DELETE FROM pagosdocventas  
DELETE FROM pasesdocvenc  
DELETE FROM planillacob  
DELETE FROM planillacob_log 
DELETE FROM planillacobdet  
DELETE FROM planillacobdet_log  
DELETE FROM regisdoc  
DELETE FROM regisdoc_log 
DELETE FROM regismov 
DELETE FROM regismov_log 
DELETE FROM regisofi 
DELETE FROM regisofi_log 
DELETE FROM talonarios  
DELETE FROM tbcomprasvales  
DELETE FROM tbdetracciones   
DELETE FROM tbpercepciones  
DELETE FROM tomainvcab  
DELETE FROM tomainvdet 
DELETE FROM valescab  
DELETE FROM valescab_log 
DELETE FROM valesconver 
DELETE FROM valesconvercosteo 
DELETE FROM valesconverdet 
DELETE FROM valesdet  
delete FROM valesdet_log  
delete FROM docventasdetlote  
delete FROM valesdetlotes  
delete FROM valestrans 
delete FROM valestransdet 
delete FROM zonas 
delete FROM preciosventa  
delete from tbsaldo_costo_kardex  
delete from tbsaldo_costo_kardex_log  
DELETE FROM retencioncab  
DELETE FROM retenciondet  
DELETE FROM retencioncab_log  
DELETE FROM retenciondet_log  
DELETE FROM clientes
DELETE FROM productos
DELETE FROM proveedores
DELETE FROM contactosclientes
DELETE FROM productosproveedor
DELETE FROM proveedoresformapagos
DELETE FROM clientesformapagos
DELETE FROM productosclientes
DELETE FROM contactosproveedores
DELETE FROM centroscosto
DELETE FROM centroscosto_log
DELETE FROM listaprecios
DELETE FROM preciosventa
DELETE FROM lotes
DELETE FROM almacenes
DELETE FROM almacenesvtas
DELETE FROM productosalmacen
DELETE FROM productosalmacenporlote
DELETE FROM almacenesubicacion
DELETE FROM vendedores
DELETE FROM choferes
DELETE FROM tiposdecambio
DELETE FROM seriexusuario
DELETE FROM tiendascliente