<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>aspnet-SistemaAdministrativoWeb-53c45fe8-ede4-4ae5-9d55-e176dba84e4e</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" Version="10.0.5" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.Google" Version="10.0.5" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="10.0.5" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.UI" Version="10.0.5" />
    <PackageReference Include="Microsoft.Data.SqlClient" Version="6.1.2" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.5" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.5" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="FralseTech.Web\**" />
    <Compile Remove="temp_codex_build\**" />
    <Compile Remove="tmp\**" />
    <Compile Remove="tmp_build\**" />
    <Compile Remove="tmp_build_*\**" />
    <Compile Remove="tmp_build_sisadm\**" />
    <Content Remove="FralseTech.Web\**" />
    <Content Remove="temp_codex_build\**" />
    <Content Remove="tmp\**" />
    <Content Remove="tmp_build\**" />
    <Content Remove="tmp_build_*\**" />
    <Content Remove="tmp_build_sisadm\**" />
    <EmbeddedResource Remove="FralseTech.Web\**" />
    <EmbeddedResource Remove="temp_codex_build\**" />
    <EmbeddedResource Remove="tmp\**" />
    <EmbeddedResource Remove="tmp_build\**" />
    <EmbeddedResource Remove="tmp_build_*\**" />
    <EmbeddedResource Remove="tmp_build_sisadm\**" />
    <None Remove="FralseTech.Web\**" />
    <None Remove="temp_codex_build\**" />
    <None Remove="tmp\**" />
    <None Remove="tmp_build\**" />
    <None Remove="tmp_build_*\**" />
    <None Remove="tmp_build_sisadm\**" />
  </ItemGroup>

</Project>
