using Microsoft.AspNetCore.Mvc.Rendering;
using SistemaControlEspaciosDeportivosWeb.ViewModels;

namespace SistemaControlEspaciosDeportivosWeb.Services;

public interface ISportCenterStoredProcedureService
{
    Task<List<SedePublicaViewModel>> HomeListarSedesAsync();
    Task<List<TipoDeportePublicoViewModel>> HomeListarTiposDeporteAsync();
    Task<List<SelectListItem>> HomeReferencialesExternosListarTiposDeporteSuperAsync();
    Task<(List<ReferencialExternoAdminItemViewModel> Items, int TotalRegistros)> HomeReferencialesExternosListarAdminAsync(string? codigoDepartamento = null, string? codigoProvincia = null, string? codigoUbigeo = null, string? buscarNombre = null, int pagina = 1, int tamanoPagina = 20, bool? soloActivos = true);
    Task<bool> HomeReferencialesExternosInactivarAsync(int id, string usuario);
    Task<bool> HomeReferencialesExternosActivarAsync(int id, string usuario);
    Task<bool> HomeReferencialesExternosActualizarAsync(int id, string nombreComplejo, string? telefonoContacto, int tipoDeporteSuperId, string? direccion, string codigoUbigeo, string usuario);
    Task<int> HomeReferencialesExternosCrearManualAsync(string nombreComplejo, int tipoDeporteSuperId, string codigoUbigeo, string? direccion, string? telefonoContacto, string? correoContacto, decimal? latitudReferencia, decimal? longitudReferencia, string? googleMapsUrl, string usuario);
    Task<List<WebBannerPublicoViewModel>> HomeListarBannersPublicosAsync();
    Task<List<PopupPromocionPublicoViewModel>> HomeListarPopupPromocionesActivasAsync();
    Task<WebBannerPublicoViewModel?> WebBannersObtenerFijoPorTipoAsync(int tipoBanner);
    Task<List<EspacioDisponibleViewModel>> HomeBuscarEspaciosDisponiblesAsync(DateOnly fecha, TimeOnly horaInicio, TimeOnly horaFin, string? codigoDepartamento, string? codigoProvincia, string? codigoUbigeo, int? tipoDeporteId, int? negocioId, bool omitirFechaHorario = false, bool buscarCercaDeMi = false, decimal? latitudUsuario = null, decimal? longitudUsuario = null, decimal? radioKm = null);
    Task<(List<EspacioDisponibleViewModel> Espacios, int TotalRegistros)> HomeBuscarEspaciosDisponiblesPaginadoAsync(DateOnly fecha, TimeOnly horaInicio, TimeOnly horaFin, string? codigoDepartamento, string? codigoProvincia, string? codigoUbigeo, int? tipoDeporteId, int? negocioId, int pagina = 1, int tamanoPagina = 9, bool omitirFechaHorario = false, bool buscarCercaDeMi = false, decimal? latitudUsuario = null, decimal? longitudUsuario = null, decimal? radioKm = null);
    Task<int> HomeSolicitarReservaPublicaAsync(SolicitudReservaPublicaFormViewModel model);
    Task<SolicitudNotificacionEmailViewModel?> HomeObtenerSolicitudParaNotificacionAsync(string codigoSolicitud);
    Task<bool> HomeMarcarSolicitudNotificadaAsync(string codigoSolicitud);
    Task<ConfiguracionClubViewModel?> ConfiguracionClubObtenerAsync(int negocioId);
    Task<OnboardingChecklistViewModel> OnboardingChecklistValidarAsync(int negocioId);
    Task<bool> ConfiguracionClubActualizarAsync(ConfiguracionClubViewModel model, string usuario);
    Task<List<SelectListItem>> ConfiguracionClubComboMonedasAsync(int negocioId);
    Task<bool> ConfiguracionClubActualizarEmisionAsync(int negocioId, bool emisionComprobantesElectronicos, bool enviarComprobanteAutomatico, bool emisionReciboInterno, string usuario);
    Task<List<SerieDocumentoComprobanteItemViewModel>> ConfiguracionSeriesDocumentoListarAsync(int negocioId);
    Task ConfiguracionSeriesDocumentoGuardarAsync(int negocioId, string codigoSunat, string serie, bool activo, string usuario);
    Task<bool> ConfiguracionSeriesDocumentoEliminarAsync(int negocioId, int id, string usuario);
    Task<List<SelectListItem>> CombosTiposDocumentoIdentidadSunatAsync();
    Task<List<SelectListItem>> CombosTiposNotaComprobanteSunatAsync(string tipoNota);
    Task<List<SelectListItem>> CombosDocumentosComprobanteNegocioAsync(int negocioId, bool? tributario = null);
    Task<List<SelectListItem>> CombosSeriesDocumentoComprobanteAsync(int negocioId, string codigoSunat);
    Task<string?> ParametrosGlobalesObtenerValorAsync(string nombreParametro);
    Task ParametrosGlobalesUpsertValorAsync(string nombreParametro, string? descripcion, string? valorParametro, string usuario);
    Task<List<SelectListItem>> UbigeoDepartamentosListarAsync();
    Task<List<SelectListItem>> UbigeoProvinciasListarAsync(string codigoDepartamento);
    Task<List<SelectListItem>> UbigeoDistritosListarAsync(string codigoProvincia, string? zona = null);
    Task<List<SelectListItem>> UbigeoZonasListarAsync(string? codigoDepartamento = null, string? codigoProvincia = null);
    Task<UbigeoLookupViewModel?> UbigeoObtenerPorCodigoAsync(string codigoUbigeo);
    Task<int> BoletinesDeportivosGuardarAsync(BoletinDeportivoGuardarViewModel model, string usuario);
    Task<List<BoletinDeportivoPublicoItemViewModel>> BoletinesDeportivosListarPublicoAsync(string? codigoDepartamento = null, string? codigoProvincia = null, string? codigoUbigeo = null, string? zona = null, int? anio = null, int? mes = null);
    Task<(List<BoletinDeportivoUsuarioItemViewModel> Boletines, int TotalRegistros)> BoletinesDeportivosListarPorUsuarioAsync(string usuarioId, int pagina = 1, int tamanoPagina = 5);
    Task<BoletinDeportivoDetalleViewModel?> BoletinesDeportivosObtenerPorIdAsync(int idBoletin);
    Task<BoletinesDeportivosAdminResumenViewModel> BoletinesDeportivosAdminResumenAsync();
    Task<(List<BoletinDeportivoAdminItemViewModel> Boletines, int TotalRegistros)> BoletinesDeportivosAdminListarAsync(bool? activo = null, string? tipoRegistro = null, string? codigoDepartamento = null, string? codigoProvincia = null, string? codigoUbigeo = null, string? zona = null, int? anio = null, int? mes = null, int pagina = 1, int tamanoPagina = 5);
    Task<bool> BoletinesDeportivosCambiarEstadoAsync(int idBoletin, bool activo, string usuario);
    Task<UsuarioPublicoPerfilViewModel?> UsuariosPublicosObtenerPerfilAsync(string usuarioId);
    Task<int> UsuariosPublicosGuardarPerfilAsync(UsuarioPublicoPerfilViewModel model, string usuario);
    Task<(List<UsuarioPublicoReservaItemViewModel> Reservas, int TotalRegistros)> UsuariosPublicosReservasListarAsync(string usuarioId, int pagina = 1, int tamanoPagina = 6);
    Task<UsuarioPublicoReservaCalendarioViewModel?> UsuariosPublicosReservaCalendarioObtenerAsync(string usuarioId, int reservaId);
    Task<int> UsuariosPublicosResenaCrearAsync(string usuarioId, UsuarioPublicoResenaGuardarViewModel model, string usuario);
    Task<List<UsuarioPublicoResenaItemViewModel>> HomeEspacioResenasListarAsync(int espacioDeportivoId);
    Task<(List<EspacioResenaAdminItemViewModel> Resenas, int TotalRegistros, int TotalVisibles, int TotalOcultas, int TotalRespondidas)> EspaciosResenasListarAsync(int negocioId, int espacioDeportivoId, int pagina = 1, int tamanoPagina = 4);
    Task<bool> EspaciosResenaGestionarAsync(EspacioResenaGestionViewModel model, string usuario);
    Task<List<SelectListItem>> DesafiosNivelesListarAsync();
    Task<List<DesafioRivalItemViewModel>> DesafiosBuscarRivalesAsync(string usuarioId, string? codigoUbigeo, string? zona, int? idDeporte, int? idNivel);
    Task<List<DesafioListadoItemViewModel>> DesafiosListarAsync(string usuarioId, string tipoListado);
    Task<(List<DesafioListadoItemViewModel> Items, int TotalRegistros)> DesafiosHistorialListarAsync(string usuarioId, int pagina = 1, int tamanoPagina = 4);
    Task<List<DesafioMensajeItemViewModel>> DesafiosMensajesListarAsync(string usuarioId, int? desafioId = null);
    Task<int> DesafiosCrearAsync(string usuarioId, DesafioCrearViewModel model, string usuario);
    Task<DesafioEmailContextViewModel?> DesafiosObtenerContextoEmailAsync(int desafioId);
    Task<int> DesafiosMensajeCrearAsync(string usuarioId, DesafioMensajeCrearViewModel model, string usuario);
    Task<bool> DesafiosCancelarAsync(int desafioId, string usuarioId, string usuario);
    Task<bool> DesafiosResponderAsync(int desafioId, string usuarioId, string estado, string usuario);
    Task<bool> DesafiosFinalizarAsync(int desafioId, string usuarioId, string usuario);

    Task<List<NegocioAccesoViewModel>> PanelListarNegociosUsuarioAsync(string usuarioId);
    Task<List<PermisoModuloViewModel>> PanelListarModulosPermitidosAsync(string usuarioId, int negocioId);
    Task<(int TotalSedes, int TotalEspacios, int ReservasHoy, decimal IngresosHoy, decimal OcupacionHoyPct, int NoShowMes, decimal TicketPromedioMes)> PanelObtenerMetricasAsync(int negocioId, DateOnly fecha, int? sedeId = null);

    Task<List<SedeItemViewModel>> SedesListarAsync(int negocioId, int? sedeId = null);
    Task<SedeFormViewModel?> SedesObtenerAsync(int negocioId, int id);
    Task<int> SedesCrearAsync(SedeFormViewModel model, string usuario);
    Task<bool> SedesActualizarAsync(SedeFormViewModel model, string usuario);
    Task<bool> SedesEliminarAsync(int negocioId, int id, string usuario);
    Task<List<SelectListItem>> SedesComboServiciosAsync();
    Task<List<SedeSerieDocumentoConfigItemViewModel>> SedesSeriesDocumentoListarAsync(int negocioId, int sedeId);
    Task SedesSeriesDocumentoGuardarAsync(int negocioId, int sedeId, string codigoSunat, int? negocioSerieId, string usuario);
    Task SedesSeriesDocumentoGuardarMultiplesAsync(int negocioId, int sedeId, string codigoSunat, IEnumerable<int> negocioSeriesIds, string usuario);

    Task<List<EspacioItemViewModel>> EspaciosListarAsync(int negocioId, int? sedeId = null);
    Task<EspacioFormViewModel?> EspaciosObtenerAsync(int negocioId, int id);
    Task<int> EspaciosCrearAsync(EspacioFormViewModel model, string usuario);
    Task<bool> EspaciosActualizarAsync(EspacioFormViewModel model, string usuario);
    Task<bool> EspaciosEliminarAsync(int negocioId, int id, string usuario);
    Task<List<SelectListItem>> EspaciosComboSedesAsync(int negocioId, int? sedeId = null);
    Task<List<SelectListItem>> EspaciosComboTiposDeporteAsync(int negocioId);
    Task<List<SelectListItem>> EspaciosComboTiposSueloAsync(int negocioId);
    Task<List<SelectListItem>> EspaciosComboCompartiblesAsync(int negocioId, int sedeId, int? espacioActualId = null);

    Task<(List<ReservaItemViewModel> Reservas, int TotalRegistros)> ReservasListarAsync(int negocioId, DateOnly? fechaDesde = null, DateOnly? fechaHasta = null, int? sedeId = null, int? espacioDeportivoId = null, int? estado = null, string? estadosCsv = null, int pagina = 1, int tamanoPagina = 20);
    Task<ReservasListadoResumenViewModel> ReservasListadoResumenAsync(int negocioId, DateOnly? fechaDesde = null, DateOnly? fechaHasta = null, int? sedeId = null, int? espacioDeportivoId = null, int? estado = null, string? estadosCsv = null);
    Task<ReservaFormViewModel?> ReservasObtenerAsync(int negocioId, int id);
    Task<int> ReservasCrearAsync(ReservaFormViewModel model, string usuario);
    Task<bool> ReservasActualizarAsync(ReservaFormViewModel model, string usuario);
    Task<bool> ReservasEliminarAsync(int negocioId, int id, string usuario);
    Task<bool> ReservasCambiarEstadoRapidoAsync(int negocioId, int id, int nuevoEstado, string usuario);
    Task<List<ReservaHistorialItemViewModel>> ReservasHistorialAsync(int negocioId, int reservaId);
    Task<ReservaRecordatorioPendienteViewModel?> ReservasObtenerParaRecordatorioAsync(int negocioId, int reservaId);
    Task<ReservaEmailContextViewModel?> ReservasObtenerContextoEmailAsync(int? negocioId, int reservaId);
    Task<List<ReservaCalendarioEventoViewModel>> ReservasCalendarioEventosAsync(int negocioId, DateOnly fechaDesde, DateOnly fechaHasta, int? sedeId = null, int? espacioDeportivoId = null, int? estado = null);
    Task<bool> ReservasMoverAsync(int negocioId, int id, DateOnly fecha, TimeOnly horaInicio, TimeOnly horaFin, string usuario);
    Task<ReservaDisponibilidadValidacionViewModel> ReservasValidarDisponibilidadAsync(int negocioId, int? reservaId, int espacioDeportivoId, DateOnly fecha, TimeOnly horaInicio, TimeOnly horaFin);
    Task<ReservaCotizacionViewModel> ReservasCotizarAsync(int negocioId, int espacioDeportivoId, DateOnly fecha, TimeOnly horaInicio, TimeOnly horaFin);
    Task<List<BloqueoHorarioItemViewModel>> BloqueosListarAsync(int negocioId, DateOnly fechaDesde, DateOnly fechaHasta, int? sedeId = null, int? espacioDeportivoId = null);
    Task<int> BloqueosCrearAsync(BloqueoHorarioFormViewModel model, string usuario);
    Task<bool> BloqueosEliminarAsync(int negocioId, int id, string usuario);
    Task<List<SelectListItem>> ReservasComboEspaciosAsync(int negocioId, int? sedeId = null);
    Task<List<SelectListItem>> ReservasComboClientesAsync(int negocioId);
    Task<List<SelectListItem>> ReservasBuscarClientesAsync(int negocioId, string? buscar = null, int? clienteId = null, int top = 50);

    Task<(List<PagoReservaResumenViewModel> Pagos, int TotalRegistros)> PagosListarAsync(int negocioId, int? sedeId = null, string? buscar = null, DateOnly? fechaDesde = null, DateOnly? fechaHasta = null, int pagina = 1, int tamanoPagina = 20);
    Task<PagoReservaEditViewModel?> PagosObtenerAsync(int negocioId, int reservaId);
    Task<int> PagosCrearAsync(PagoFormViewModel model, string usuario);
    Task<bool> PagosActualizarAsync(int negocioId, int pagoId, string? observacion, string usuario);
    Task<bool> PagosEliminarAsync(int negocioId, int id, string usuario);
    Task<bool> PagosEliminarPorReservaAsync(int negocioId, int reservaId, string usuario);
    Task<List<SelectListItem>> PagosComboReservasAsync(int negocioId, int? sedeId = null);
    Task<List<SelectListItem>> PagosBuscarReservasAsync(int negocioId, string? buscar = null, int? reservaId = null, int top = 30);
    Task<List<SelectListItem>> PagosComboFormasPagoAsync(int negocioId);

    Task<(List<ComprobanteItemViewModel> Comprobantes, int TotalRegistros)> ComprobantesListarAsync(int negocioId, int? sedeId = null, string? buscar = null, string? codigoDocumento = null, DateOnly? fechaDesde = null, DateOnly? fechaHasta = null, int pagina = 1, int tamanoPagina = 20);
    Task<ComprobanteFormViewModel?> ComprobantesObtenerAsync(int negocioId, int id);
    Task<ComprobanteVisualizacionViewModel?> ComprobantesObtenerVisualizacionAsync(int negocioId, int id);
    Task<int> ComprobantesCrearAsync(ComprobanteFormViewModel model, string usuario);
    Task<bool> ComprobantesActualizarAsync(ComprobanteFormViewModel model, string usuario);
    Task<bool> ComprobantesEliminarAsync(int negocioId, int id, string usuario);
    Task<List<SelectListItem>> ComprobantesComboReservasAsync(int negocioId, int? sedeId = null);
    Task<List<SelectListItem>> ComprobantesBuscarReservasPagadasAsync(int negocioId, string? buscar = null, int? reservaId = null, int top = 30);
    Task<ComprobanteReservaContextoViewModel?> ComprobantesObtenerContextoReservaAsync(int negocioId, int reservaId, string? codigoSunat = null);

    Task<(List<ClienteItemViewModel> Clientes, int TotalRegistros, int TotalActivos, int TotalInactivos)> ClientesListarAsync(int negocioId, bool? activo = null, string? buscar = null, int pagina = 1, int tamanoPagina = 20);
    Task<ClienteFormViewModel?> ClientesObtenerAsync(int negocioId, int id);
    Task<int> ClientesCrearAsync(ClienteFormViewModel model, string usuario);
    Task<bool> ClientesActualizarAsync(ClienteFormViewModel model, string usuario);
    Task<bool> ClientesEliminarAsync(int negocioId, int id, string usuario);

    Task<List<ReporteOcupacionItemViewModel>> ReportesOcupacionPorEspacioAsync(int negocioId, DateOnly fechaDesde, DateOnly fechaHasta, int? sedeId = null);
    Task<List<ReporteIngresoDiaItemViewModel>> ReportesIngresosPorDiaAsync(int negocioId, DateOnly fechaDesde, DateOnly fechaHasta, int? sedeId = null);
    Task<List<ReporteReservaDiaItemViewModel>> ReportesReservasPorDiaAsync(int negocioId, DateOnly fechaDesde, DateOnly fechaHasta, int? sedeId = null);
    Task<ReporteResumenOperativoViewModel> ReportesResumenOperativoAsync(int negocioId, DateOnly fechaDesde, DateOnly fechaHasta, int? sedeId = null);
    Task<ReporteResumenCobranzaViewModel> ReportesResumenCobranzaAsync(int negocioId, DateOnly fechaDesde, DateOnly fechaHasta, int? sedeId = null);
    Task<List<ReportePagoDetalleItemViewModel>> ReportesDetallePagosAsync(int negocioId, DateOnly fechaDesde, DateOnly fechaHasta, int? sedeId = null);
    Task<List<ReporteReservaDetalleItemViewModel>> ReportesDetalleReservasAsync(int negocioId, DateOnly fechaDesde, DateOnly fechaHasta, int? sedeId = null);
    Task<int> NotificacionesContarNoLeidasAsync(int negocioId);
    Task<List<NotificacionNegocioItemViewModel>> NotificacionesListarAsync(int negocioId, int top = 15);
    Task<bool> NotificacionesMarcarLeidaAsync(int negocioId, int notificacionId, string? userId);
    Task<int> NotificacionesMarcarTodasLeidasAsync(int negocioId, string? userId);

    Task<List<SolicitudPublicaItemViewModel>> SolicitudesPublicasListarAsync(int negocioId, DateOnly? fechaDesde = null, DateOnly? fechaHasta = null, int? estado = null);
    Task<bool> SolicitudesPublicasActualizarEstadoAsync(SolicitudEstadoFormViewModel model, string usuario);
    Task<int> SolicitudesPublicasConvertirAReservaAsync(SolicitudConvertirFormViewModel model, string usuario);
    Task<string> HomeSolicitarAltaClubAsync(AltaClubSolicitudFormViewModel model);
    Task<string> HomeRegistrarClubConPruebaAsync(AltaClubSolicitudFormViewModel model, string usuarioId);
    Task<(List<AltaClubItemViewModel> Solicitudes, int TotalRegistros, int TotalPendientes, int TotalAprobados, int TotalRechazados)> AltasClubesListarAsync(int? estado = null, int pagina = 1, int tamanoPagina = 20);
    Task<AltaClubItemViewModel?> AltasClubesObtenerPorIdAsync(int id);
    Task<bool> AltasClubesAprobarAsync(int id, string usuario, string? comentarioGestion = null, int diasPrueba = 15);
    Task<bool> AltasClubesRechazarAsync(int id, string usuario, string? comentarioGestion = null);

    Task<List<UsuarioNegocioItemViewModel>> UsuariosNegocioListarAsync(int negocioId, int? sedeId = null);
    Task<List<SelectListItem>> UsuariosNegocioRolesListarAsync();
    Task<bool> UsuariosNegocioAsignarPorCorreoAsync(int negocioId, string correo, int rolNegocio, int? sedeId, string usuario);
    Task<bool> UsuariosNegocioActualizarRolAsync(int negocioId, int usuarioNegocioId, int rolNegocio, int? sedeId, string usuario);
    Task<bool> UsuariosNegocioDesactivarAsync(int negocioId, int usuarioNegocioId, string usuario);
    Task<List<UsuarioNegocioPermisoModuloViewModel>> UsuariosNegocioPermisosListarAsync(int negocioId, int usuarioNegocioId);
    Task<bool> UsuariosNegocioPermisoGuardarAsync(int negocioId, int usuarioNegocioId, UsuarioNegocioPermisoModuloViewModel model, string usuario);

    Task<(List<PromocionItemViewModel> Promociones, int TotalRegistros)> PromocionesListarAsync(int negocioId, int? sedeId = null, DateOnly? fechaDesde = null, DateOnly? fechaHasta = null, bool? soloActivos = true, int pagina = 1, int tamanoPagina = 20);
    Task<PromocionFormViewModel?> PromocionesObtenerAsync(int negocioId, int id);
    Task<int> PromocionesCrearAsync(PromocionFormViewModel model, string usuario);
    Task<bool> PromocionesActualizarAsync(PromocionFormViewModel model, string usuario);
    Task<bool> PromocionesEliminarAsync(int negocioId, int id, string usuario);
    Task<(List<CuponItemViewModel> Cupones, int TotalRegistros)> CuponesListarAsync(int negocioId, int? sedeId = null, DateOnly? fechaDesde = null, DateOnly? fechaHasta = null, string? estado = "vigentes", int pagina = 1, int tamanoPagina = 20);
    Task<CuponFormViewModel?> CuponesObtenerAsync(int negocioId, int id);
    Task<int> CuponesCrearAsync(CuponFormViewModel model, string usuario);
    Task<bool> CuponesActualizarAsync(CuponFormViewModel model, string usuario);
    Task<bool> CuponesEliminarAsync(int negocioId, int id, string usuario);
    Task<CuponValidacionViewModel> CuponesValidarAsync(int negocioId, int? sedeId, int espacioDeportivoId, string? codigoCupon, decimal montoBase);

    Task<List<MonedaMaestroItemViewModel>> MaestrosMonedasListarAsync(int negocioId);
    Task<List<SelectListItem>> MaestrosMonedasSuperListarAsync();
    Task<int> MaestrosMonedasCrearAsync(int negocioId, int monedaSuperId, bool activo, string usuario);
    Task<bool> MaestrosMonedasActualizarAsync(int negocioId, int id, bool activo, string usuario);
    Task<bool> MaestrosMonedasEliminarAsync(int negocioId, int id, string usuario);

    Task<List<MaestroCatalogoItemViewModel>> MaestrosTiposSueloListarAsync(int negocioId);
    Task<List<SelectListItem>> MaestrosTiposSueloSuperListarAsync();
    Task<int> MaestrosTiposSueloCrearAsync(int negocioId, int tipoSueloSuperId, bool activo, string usuario);
    Task<bool> MaestrosTiposSueloActualizarAsync(int negocioId, int id, bool activo, string usuario);
    Task<bool> MaestrosTiposSueloEliminarAsync(int negocioId, int id, string usuario);

    Task<List<MaestroCatalogoItemViewModel>> MaestrosTiposDeporteListarAsync(int negocioId);
    Task<List<SelectListItem>> MaestrosTiposDeporteSuperListarAsync();
    Task<int> MaestrosTiposDeporteCrearAsync(int negocioId, int tipoDeporteSuperId, bool activo, string usuario);
    Task<bool> MaestrosTiposDeporteActualizarAsync(int negocioId, int id, bool activo, string usuario);
    Task<bool> MaestrosTiposDeporteEliminarAsync(int negocioId, int id, string usuario);

    Task<List<MaestroCatalogoItemViewModel>> MaestrosFormasPagoListarAsync(int negocioId);
    Task<int> MaestrosFormasPagoCrearAsync(int negocioId, string nombre, bool activo, string usuario);
    Task<bool> MaestrosFormasPagoActualizarAsync(int negocioId, int id, string nombre, bool activo, string usuario);
    Task<bool> MaestrosFormasPagoEliminarAsync(int negocioId, int id, string usuario);
    Task<List<SelectListItem>> MaestrosTiposDocumentoComprobanteSuperListarAsync();
    Task<List<TipoDocumentoComprobanteNegocioItemViewModel>> MaestrosTiposDocumentoComprobanteListarAsync(int negocioId);
    Task<int> MaestrosTiposDocumentoComprobanteCrearAsync(int negocioId, string codigoSunat, bool activo, string usuario);
    Task<bool> MaestrosTiposDocumentoComprobanteActualizarAsync(int negocioId, int id, bool activo, string usuario);
    Task<bool> MaestrosTiposDocumentoComprobanteEliminarAsync(int negocioId, int id, string usuario);

    Task<List<BannerAdminItemViewModel>> BannersAdminListarAsync(bool? soloActivos = null);
    Task<int> BannersAdminGuardarAsync(BannerAdminFormViewModel model, string usuario);
    Task<bool> BannersAdminEliminarAsync(int id, string usuario);
    Task<List<PopupPromocionAdminItemViewModel>> PopupPromocionesAdminListarAsync(bool? soloActivos = null);
    Task<int> PopupPromocionesAdminGuardarAsync(PopupPromocionAdminFormViewModel model, string usuario);
    Task<bool> PopupPromocionesAdminEliminarAsync(int idPopupPromocion, string usuario);
    Task<bool> PopupPromocionesAdminCambiarEstadoAsync(int idPopupPromocion, bool activo, string usuario);
    Task<(List<PlataformaNegocioLimiteItemViewModel> Negocios, int TotalRegistros)> PlataformaNegociosListarAsync(string? buscar = null, string? estadoContrato = null, int pagina = 1, int tamanoPagina = 20);
    Task<(string? Correo, string? NombreDestino, string? Telefono)> PlataformaNegocioObtenerContactoCorreoAsync(int negocioId);
    Task<bool> PlataformaNegocioActualizarLimitesAsync(int negocioId, string tipoPlan, int sedesPermitidas, int espaciosPermitidos, int usuariosPermitidos, string usuario);
    Task<(string TipoPlan, int SedesPermitidas, int EspaciosPermitidos, int UsuariosPermitidos)> NegocioObtenerLimitesOperativosAsync(int negocioId);
    Task<bool> PlataformaNegocioActivarContratoAsync(int negocioId, string tipoCobro, DateOnly fechaDesde, DateOnly fechaHasta, int diasGracia, string usuario);
    Task<bool> PlataformaNegocioRenovarContratoAsync(int negocioId, string usuario);
    Task<bool> PlataformaNegocioFinalizarContratoAsync(int negocioId, string usuario);
    Task<bool> PlataformaNegocioExtenderPruebaAsync(int negocioId, int diasExtra, string? observacion, string usuario);
    Task<bool> PlataformaNegocioAplicarGraciaManualAsync(int negocioId, int diasExtra, string? observacion, string usuario);
    Task<bool> PlataformaNegocioCambiarPlanAsync(int negocioId, string tipoCobro, DateOnly fechaDesde, DateOnly fechaHasta, int diasGracia, string? observacion, string usuario);
    Task<bool> PlataformaNegocioSuspenderServicioAsync(int negocioId, string motivo, string? observacion, string usuario);
    Task<bool> PlataformaNegocioReactivarServicioAsync(int negocioId, string? observacion, string usuario);
    Task<int> PlataformaSuspenderSuscripcionesVencidasAsync(string usuario);
    Task<bool> PlataformaNegocioDarBajaAsync(int negocioId, string motivo, string? observacion, string confirmacionNombre, string usuario);
    Task<bool> PlataformaNegocioReactivarComplejoAsync(int negocioId, string? observacion, string usuario);
    Task<List<PlataformaNegocioSuscripcionMovimientoViewModel>> PlataformaNegocioHistorialComercialAsync(int negocioId, int top = 8);
    Task<bool> PlataformaNegocioRegistrarPagoSuscripcionAsync(int negocioId, string tipoPago, string estadoPago, decimal monto, string moneda, DateTime fechaPago, DateOnly? fechaVencimiento, string? operacionNumero, string? entidadFinanciera, string? referenciaExterna, string? observacion, string? accionAplicacion, bool aplicarAlConfirmar, string? tipoCobroObjetivo, string? planComercialObjetivo, int? sedesPermitidasObjetivo, int? espaciosPermitidosObjetivo, int? usuariosPermitidosObjetivo, DateOnly? fechaInicioPlanObjetivo, int? diasGraciaObjetivo, string usuario);
    Task<(List<PlataformaNegocioSuscripcionPagoViewModel> Pagos, int CantidadPagos, decimal MontoTotalPagado, DateTime? UltimaFechaPago, decimal? UltimoMonto, string? UltimoTipoPago)> PlataformaNegocioPagosSuscripcionAsync(int negocioId, int top = 8);
    Task<bool> PlataformaNegocioConfirmarPagoSuscripcionAsync(int negocioId, int pagoId, string usuario);
    Task<MiSuscripcionNegocioViewModel?> MiSuscripcionObtenerAsync(int negocioId);

    Task<List<ReservaRecordatorioPendienteViewModel>> ReservasRecordatoriosPendientesAsync(DateTime fechaHoraActual);
    Task<bool> ReservasMarcarRecordatorioEnviadoAsync(int negocioId, int reservaId, string usuario);
    Task<int> ReservasAutoNoShowAsync(DateTime fechaHoraActual, string usuario);
    Task<int> ReservasAutoCancelarNoConfirmadasAsync(DateTime fechaHoraActual, string usuario);
}
